id: P713072EB
initial_creation_type: input
source_metadata:
  title: Gyalwa Yangönpa
  language: bo
  description: 'Texts by and about the famous Drukpa Kagyü adept Yangönpa Gyaltsen
    Pal (yang dgon pa rgyal mtshan dpal, 1213–1258):'
  volume:
    ba74ac54be0c4517a604d8dad6aa8147:
      title: 'The Liberating Guide: A Prayer to Gyalwa Yangönpa'
      parent: Prayers
created_at: '2022-02-28T23:29:50.470633'
last_modified_at: '2022-02-28T23:29:50.470635'
statistics:
  total_words: 384
  total_non_words: 14
quality:
  non_words_ratio: 0.04
